# Generated by Django 3.2.16 on 2022-12-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sure_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sure',
            options={'get_latest_by': ['id']},
        ),
    ]
