# Generated by Django 3.2.16 on 2022-12-04 15:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sure_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sure',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
