# Generated by Django 3.2.16 on 2022-12-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221204_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sure',
            name='q22',
            field=models.IntegerField(
                choices=[
                    (1, 'Não Importante'),
                    (2, 'Pouco Importante'),
                    (3, 'Importante'),
                    (4, 'Muito Importante'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='sure',
            name='q23',
            field=models.IntegerField(
                choices=[
                    (1, 'Não Importante'),
                    (2, 'Pouco Importante'),
                    (3, 'Importante'),
                    (4, 'Muito Importante'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='sure',
            name='q24',
            field=models.IntegerField(
                choices=[
                    (1, 'Não Importante'),
                    (2, 'Pouco Importante'),
                    (3, 'Importante'),
                    (4, 'Muito Importante'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='sure',
            name='q25',
            field=models.IntegerField(
                choices=[
                    (1, 'Não Importante'),
                    (2, 'Pouco Importante'),
                    (3, 'Importante'),
                    (4, 'Muito Importante'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='sure',
            name='q26',
            field=models.IntegerField(
                choices=[
                    (1, 'Não Importante'),
                    (2, 'Pouco Importante'),
                    (3, 'Importante'),
                    (4, 'Muito Importante'),
                ]
            ),
        ),
    ]
